
#define anIna 0 
#define anInb 1
#define anInc 2

int iAnVala;  //Analog in a
int iAnValb;  //Analog in b
int iAnValc;  //Analog in c
int LedOut1 = 3; //Out to led red
int LedOut2 = 5; //Out to led blue
int LedOut3 = 6; //Out to led green
int Delay;    //pause time

void setup() {
Serial.begin(9600);
}

void readSensors() {

Delay = 150;

iAnVala = analogRead(anIna);   // read a value from sensor a
delay(Delay);     /* Stop the program for a moment. */
Serial.print("A");  //Tag A   Serial prints are to see what values are being generated by the sensors
Serial.println(iAnVala);  //Send serial data
analogWrite(LedOut1,255-iAnVala);   //Red LED Analog output to led

iAnValb = analogRead(anInb);   // read a value from sensor b
delay(Delay);     /* Stop the program for a moment. */
Serial.print("B");  //Tag B
Serial.println(iAnValb);  //Send serial data
analogWrite(LedOut2,255-iAnValb);   //Blue LED

iAnValc = analogRead(anInc);   // read a value from sensor c
delay(Delay);     /* Stop the program for a moment. */
Serial.print("C");  //Identify C
Serial.println(iAnValc);  //Send serial data
analogWrite(LedOut3,255-iAnValc);  //Green LED

}

void loop() {
  
}
